<a href="https://colab.research.google.com/github/sthamamta/RL/blob/main/Logictronix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np

class FeatureVector:
    result = []
    res_output = []

    def find_soln(cls, x):
      cls.result.append(x)
      if(len(cls.result)<3):
        print(None)
      else:
        res_output = cls.result[len(cls.result)-3:len(cls.result)+1]
        res_output.reverse()
        print(np.array(res_output))

fv = FeatureVector()
fv.find_soln([1,2,3,4,5])
fv.find_soln([6,2,3,4,5])
fv.find_soln([7,2,3,4,5])
fv.find_soln([8,2,9,4,5])
fv.find_soln([9,2,9,4,5])



None
None
[[7 2 3 4 5]
 [6 2 3 4 5]
 [1 2 3 4 5]]
[[8 2 9 4 5]
 [7 2 3 4 5]
 [6 2 3 4 5]]
[[9 2 9 4 5]
 [8 2 9 4 5]
 [7 2 3 4 5]]
